### ISSUE TITLE
安装后怎么使用

### ISSUE THREAD

**Issue by vagranter** [wupco/weblogger#1]
安装后显示如下：
all ok! please include /tmp/2076e656be7462bfd8ed6e26b768badc/weblogpro.php
managepath : /var/www/html/ed66ed39f2aa4727676e562f6d5086ad/90d40910b94e648bc36d68b87ad09ce9/managelog.php
然后怎么用呢？

**Comment by wupco** [comment]
更详细说明和帮助： https://gist.github.com/wupco/ee26f88656fbf36d014f49b4ac47ddc8

**Comment by vagranter** [comment]
无法打开链接https://gist.github.com/wupco/ee26f88656fbf36d014f49b4ac47ddc8

**Comment by wupco** [comment]
> 无法打开链接https://gist.github.com/wupco/ee26f88656fbf36d014f49b4ac47ddc8

gist.github.com需要翻墙
